[project]
name = "wdlunittests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pytest>=8.3.4",
    "pytest-recording>=0.13.2",
    "sh>=2.1.0",
    "tenacity>=9.0.0",
    "vcrpy>=7.0.0",
]
