name: API Tests

on:
  push:
    branches:
      - main
      - dev
      - test-api
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch-event]

jobs:
  api-tests:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.8"

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Dispatch event information
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo PROOF-API SHA: ${{ github.event.client_payload.sha }}
          echo PROOF-API REF: ${{ github.event.client_payload.ref }}

      - name: Load secrets
        id: load-secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PROOF_API_TOKEN_DEV: "op://PROOF/PROOF_Test_User/dev token"
          PATH_ROOTS: "op://PROOF/PROOF_PATH_ROOTS/credential"

      - name: Run tests
        run: make test_api_cached
