name: API Tests

on:
  push:
    branches:
      - main
      - dev
      - test-api
  pull_request:
  workflow_dispatch:

jobs:
  api-tests:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.8"

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PROOF_API_TOKEN_DEV: ${{ secrets.PROOF_API_TOKEN_DEV }}
          PATH_ROOTS: ${{ secrets.PATH_ROOTS }}

      - name: Run tests
        env:
          PROOF_API_TOKEN_DEV: ${{ steps.load-secrets.outputs.PROOF_API_TOKEN_DEV }}
          PATH_ROOTS: ${{ steps.load-secrets.outputs.PROOF_API_TOKEN_DEV }}
        run: make test_api_cached
