name: WDL Docs

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  build-docs:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update stable && rustup default stable

      - name: Build Sprocket
        run: |
          cargo install sprocket --locked

      - name: Build docs
        run: |
          sprocket dev doc -v --homepage README.md .
          cp -r assets docs/
