name: WDL Docs

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  build-docs:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update stable && rustup default stable

      - name: Build Sprocket
        run: |
          cargo install sprocket --locked

      - name: Build docs
        run: |
          # Drop missingValue dir since docs will fail with it
          rm -rf missingValue
          # Drop a few dirs that have a few lines that need manual fixing
          rm -rf arrayOperations gpuAlloc
          # Join WDL dir specific README's into .wdl files
          uv run make-preambles.py
          # Build docs
          sprocket dev doc -v --homepage assets/docs.md .
          # Copy assets to docs directory
          cp -r assets docs/

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
