name: WDL Docs

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  build-docs:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update stable && rustup default stable

      - name: Build Sprocket
        run: |
          cargo install sprocket@0.16.0 --locked

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.10"
          python-version: 3.13.5

      - name: Build docs
        run: |
          # Join WDL dir specific README's into .wdl files
          uv run make-preambles.py
          # Build docs
          sprocket dev doc -v --homepage assets/docs.md --logo assets/fredhutch-logo.svg .
          # Copy assets to docs directory
          cp -r assets docs/

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
