name: Cromwell Test Run

on:
  workflow_dispatch:

jobs:
  testrun:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        wdl:
          - helloHostname/helloHostname.wdl
          - helloModuleHostname/helloModuleHostname.wdl
          - helloDockerHostname/helloDockerHostname.wdl
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      -
        name: Pull Cromwell Jarfile
        run: wget -q https://github.com/broadinstitute/cromwell/releases/download/86/cromwell-86.jar
      -
        name: Execute Test Run of WDL Workflows
        run: java -jar cromwell-86.jar run ${{ matrix.wdl }}

