name: Validate Cromwell Caching

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate-cromwell-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Download Cromwell
        run: |
          wget https://github.com/broadinstitute/cromwell/releases/download/85/cromwell-85.jar
          
      - name: First run
        id: first-run
        run: |
          echo "Running first execution..."
          start_time=$(date +%s)
          java -jar cromwell-85.jar run cacheTest/cacheTest.wdl -i cacheTest/inputs.json -o cacheTest/options.json
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "first_duration=$duration" >> $GITHUB_OUTPUT
          
          # Find the most recent workflow directory
          workflow_dir=$(ls -td cromwell-executions/CacheTest/*/ | head -1)
          workflow_id=$(basename "$workflow_dir")
          echo "First workflow ID: $workflow_id"
          
          # Find the output file
          output_file="$workflow_dir/call-GenerateTimestamp/execution/output.txt"
          if [ ! -f "$output_file" ]; then
            echo "::error::Could not find output.txt at $output_file"
            exit 1
          fi
          execution_id=$(grep "Execution ID:" "$output_file" | cut -d' ' -f3)
          echo "first_execution_id=$execution_id" >> $GITHUB_OUTPUT
          echo "first_workflow_id=$workflow_id" >> $GITHUB_OUTPUT
          echo "First run output file: $output_file"
          cat "$output_file"
          
      - name: Second run (should use cache)
        id: second-run
        run: |
          echo "Running second execution..."
          start_time=$(date +%s)
          java -jar cromwell-85.jar run cacheTest/cacheTest.wdl -i cacheTest/inputs.json -o cacheTest/options.json
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "second_duration=$duration" >> $GITHUB_OUTPUT
          
          # Find the most recent workflow directory (different from the first one)
          workflow_dir=$(ls -td cromwell-executions/CacheTest/*/ | grep -v "${{ steps.first-run.outputs.first_workflow_id }}" | head -1)
          workflow_id=$(basename "$workflow_dir")
          echo "Second workflow ID: $workflow_id"
          
          # Find the output file
          output_file="$workflow_dir/call-GenerateTimestamp/execution/output.txt"
          if [ ! -f "$output_file" ]; then
            echo "::error::Could not find output.txt at $output_file"
            exit 1
          fi
          execution_id=$(grep "Execution ID:" "$output_file" | cut -d' ' -f3)
          echo "second_execution_id=$execution_id" >> $GITHUB_OUTPUT
          echo "second_workflow_id=$workflow_id" >> $GITHUB_OUTPUT
          echo "Second run output file: $output_file"
          cat "$output_file"

      - name: Validate caching behavior
        run: |
          echo "First run duration: ${{ steps.first-run.outputs.first_duration }} seconds"
          echo "Second run duration: ${{ steps.second-run.outputs.second_duration }} seconds"
          echo "First execution ID: ${{ steps.first-run.outputs.first_execution_id }}"
          echo "Second execution ID: ${{ steps.second-run.outputs.second_execution_id }}"
          
          if [ -z "${{ steps.first-run.outputs.first_execution_id }}" ] || [ -z "${{ steps.second-run.outputs.second_execution_id }}" ]; then
            echo "::error::Failed to extract execution IDs from output files"
            exit 1
          fi
          
          # Verify execution IDs match (indicating cache was used)
          if [ "${{ steps.first-run.outputs.first_execution_id }}" != "${{ steps.second-run.outputs.second_execution_id }}" ]; then
            echo "::error::Cache validation failed! Execution IDs don't match between runs."
            exit 1
          fi
          
          # Verify second run was significantly faster (< 50% of first run time)
          if [ ${{ steps.second-run.outputs.second_duration }} -gt $(( ${{ steps.first-run.outputs.first_duration }} / 2 )) ]; then
            echo "::error::Cache validation failed! Second run took too long (${steps.second-run.outputs.second_duration}s), suggesting cache wasn't used."
            exit 1
          fi
          
          echo "Cache validation passed!"
