name: Test slack webhook

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Fizzbuzz
        id: process-changes
        run: |
          failed_cassettes=("tests/cromwellapi/cassettes/test-abort/test_abort[helloHostname].yaml",
          "tests/cromwellapi/cassettes/test-failures/test_failures_final.yaml")
          length_failed_cassettes=${#failed_cassettes[@]}
          echo "length_failed_cassettes=$length_failed_cassettes" >> $GITHUB_OUTPUT

      - name: Send message to Slack
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
              -H 'Content-Type: application/json' \
              -d '{
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": ":white_check_mark: *API Tests - Rewrite Cassettes Finished*\n*Repo:* <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>\n*Run on Branch:* `${{ github.ref_name }}`\n*Run on Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>\n*Number of failed cassettes:* ${{ steps.process-changes.outputs.length_failed_cassettes }}\n*Details:* <details><summary>Details</summary>\n<p>\n\n- Some\n - Things\n\n</p>\n/details>\n"
                    }
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Go to run"
                        },
                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                      }
                    ]
                  }
                ]
              }'
