name: Test slack webhook

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H 'Content-Type: application/json' \
          -d '{
            "text": "Testing from repo: ${{ github.repository }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Build Status:* Success\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}"
                }
              }
            ]
          }'
