name: WOMtool Validation of WDL Script

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  womtoolval:
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wdl:
          - helloHostname
          - helloModuleHostname
          - helloDockerHostname
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      -
        name: Pull WOMtool Jarfile
        run: wget -q https://github.com/broadinstitute/cromwell/releases/download/86/womtool-86.jar
      -
        name: Validate WDL Scripts
        run: java -jar womtool-86.jar validate ${{ matrix.wdl }}/${{ matrix.wdl }}.wdl -i ${{ matrix.wdl }}/inputs.json



